<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CobranzaDiariaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $registros = [
            [
                'recibo' => 2,
                'fecha_cobro' => '2010-05-19',
                'hora' => '14:01:07',
                'alumno' => 18,
                'importe_cobro' => 1791,
                'tipo_pago_1' => 1,
                'importe_pago_1' => 1791,
                'referencia_1' => '',
                'tipo_pago_2' => 0,
                'importe_pago_2' => 0,
                'referencia_2' => '',
                'cajero' => 1,
                'quien_paga' => 1,
                'comentario' => '',
                'comentario_ad' => '',
                'cuen_banco' => 0,
                'referencia' => '',
                'importe' => 0,
            ],
            [
                'recibo' => 3,
                'fecha_cobro' => '2010-05-19',
                'hora' => '14:04:44',
                'alumno' => 16,
                'importe_cobro' => 1551,
                'tipo_pago_1' => 7,
                'importe_pago_1' => 1551,
                'referencia_1' => '',
                'tipo_pago_2' => 0,
                'importe_pago_2' => 0,
                'referencia_2' => '',
                'cajero' => 1,
                'quien_paga' => 1,
                'comentario' => '',
                'comentario_ad' => '',
                'cuen_banco' => 0,
                'referencia' => '',
                'importe' => 0,
            ],
            [
                'recibo' => 4,
                'fecha_cobro' => '2010-05-19',
                'hora' => '14:05:46',
                'alumno' => 25,
                'importe_cobro' => 1551,
                'tipo_pago_1' => 7,
                'importe_pago_1' => 1551,
                'referencia_1' => '',
                'tipo_pago_2' => 0,
                'importe_pago_2' => 0,
                'referencia_2' => '',
                'cajero' => 1,
                'quien_paga' => 1,
                'comentario' => '',
                'comentario_ad' => '',
                'cuen_banco' => 0,
                'referencia' => '',
                'importe' => 0,
            ],
            [
                'recibo' => 5,
                'fecha_cobro' => '2010-05-19',
                'hora' => '14:07:17',
                'alumno' => 24,
                'importe_cobro' => 1551,
                'tipo_pago_1' => 7,
                'importe_pago_1' => 1551,
                'referencia_1' => '',
                'tipo_pago_2' => 0,
                'importe_pago_2' => 0,
                'referencia_2' => '',
                'cajero' => 1,
                'quien_paga' => 1,
                'comentario' => '',
                'comentario_ad' => '',
                'cuen_banco' => 0,
                'referencia' => '',
                'importe' => 0,
            ],
            [
                'recibo' => 6,
                'fecha_cobro' => '2010-05-19',
                'hora' => '14:12:47',
                'alumno' => 26,
                'importe_cobro' => 2101,
                'tipo_pago_1' => 7,
                'importe_pago_1' => 2101,
                'referencia_1' => '',
                'tipo_pago_2' => 0,
                'importe_pago_2' => 0,
                'referencia_2' => '',
                'cajero' => 1,
                'quien_paga' => 1,
                'comentario' => '',
                'comentario_ad' => '',
                'cuen_banco' => 0,
                'referencia' => '',
                'importe' => 0,
            ],
            [
                'recibo' => 7,
                'fecha_cobro' => '2010-05-19',
                'hora' => '14:13:18',
                'alumno' => 23,
                'importe_cobro' => 1861,
                'tipo_pago_1' => 7,
                'importe_pago_1' => 1861,
                'referencia_1' => '',
                'tipo_pago_2' => 0,
                'importe_pago_2' => 0,
                'referencia_2' => '',
                'cajero' => 1,
                'quien_paga' => 1,
                'comentario' => '',
                'comentario_ad' => '',
                'cuen_banco' => 0,
                'referencia' => '',
                'importe' => 0,
            ],
            [
                'recibo' => 8,
                'fecha_cobro' => '2010-05-10',
                'hora' => '15:32:28',
                'alumno' => 19,
                'importe_cobro' => 1861,
                'tipo_pago_1' => 7,
                'importe_pago_1' => 1861,
                'referencia_1' => '',
                'tipo_pago_2' => 0,
                'importe_pago_2' => 0,
                'referencia_2' => '',
                'cajero' => 1,
                'quien_paga' => 1,
                'comentario' => '',
                'comentario_ad' => '',
                'cuen_banco' => 0,
                'referencia' => '',
                'importe' => 0,
            ],
            [
                'recibo' => 9,
                'fecha_cobro' => '2010-05-10',
                'hora' => '15:33:11',
                'alumno' => 14,
                'importe_cobro' => 1861,
                'tipo_pago_1' => 7,
                'importe_pago_1' => 1861,
                'referencia_1' => '',
                'tipo_pago_2' => 0,
                'importe_pago_2' => 0,
                'referencia_2' => '',
                'cajero' => 1,
                'quien_paga' => 1,
                'comentario' => '',
                'comentario_ad' => '',
                'cuen_banco' => 0,
                'referencia' => '',
                'importe' => 0,
            ],
            [
                'recibo' => 10,
                'fecha_cobro' => '2010-05-10',
                'hora' => '15:33:52',
                'alumno' => 22,
                'importe_cobro' => 1861,
                'tipo_pago_1' => 7,
                'importe_pago_1' => 1861,
                'referencia_1' => '',
                'tipo_pago_2' => 0,
                'importe_pago_2' => 0,
                'referencia_2' => '',
                'cajero' => 1,
                'quien_paga' => 1,
                'comentario' => '',
                'comentario_ad' => '',
                'cuen_banco' => 0,
                'referencia' => '',
                'importe' => 0,
            ],
            [
                'recibo' => 11,
                'fecha_cobro' => '2010-05-19',
                'hora' => '15:34:46',
                'alumno' => 12,
                'importe_cobro' => 2101,
                'tipo_pago_1' => 7,
                'importe_pago_1' => 2101,
                'referencia_1' => '',
                'tipo_pago_2' => 0,
                'importe_pago_2' => 0,
                'referencia_2' => '',
                'cajero' => 1,
                'quien_paga' => 1,
                'comentario' => '',
                'comentario_ad' => '',
                'cuen_banco' => 0,
                'referencia' => '',
                'importe' => 0,
            ],
            [
                'recibo' => 12,
                'fecha_cobro' => '2010-05-19',
                'hora' => '15:35:32',
                'alumno' => 33,
                'importe_cobro' => 1929,
                'tipo_pago_1' => 7,
                'importe_pago_1' => 1929,
                'referencia_1' => '',
                'tipo_pago_2' => 0,
                'importe_pago_2' => 0,
                'referencia_2' => '',
                'cajero' => 1,
                'quien_paga' => 1,
                'comentario' => '',
                'comentario_ad' => '',
                'cuen_banco' => 0,
                'referencia' => '',
                'importe' => 0,
            ],
            [
                'recibo' => 13,
                'fecha_cobro' => '2010-05-19',
                'hora' => '15:36:14',
                'alumno' => 36,
                'importe_cobro' => 1551,
                'tipo_pago_1' => 7,
                'importe_pago_1' => 1551,
                'referencia_1' => '',
                'tipo_pago_2' => 0,
                'importe_pago_2' => 0,
                'referencia_2' => '',
                'cajero' => 1,
                'quien_paga' => 1,
                'comentario' => '',
                'comentario_ad' => '',
                'cuen_banco' => 0,
                'referencia' => '',
                'importe' => 0,
            ],
            [
                'recibo' => 14,
                'fecha_cobro' => '2010-05-19',
                'hora' => '15:37:01',
                'alumno' => 21,
                'importe_cobro' => 1861,
                'tipo_pago_1' => 7,
                'importe_pago_1' => 1861,
                'referencia_1' => '',
                'tipo_pago_2' => 0,
                'importe_pago_2' => 0,
                'referencia_2' => '',
                'cajero' => 1,
                'quien_paga' => 1,
                'comentario' => '',
                'comentario_ad' => '',
                'cuen_banco' => 0,
                'referencia' => '',
                'importe' => 0,
            ],
            [
                'recibo' => 15,
                'fecha_cobro' => '2010-05-19',
                'hora' => '15:38:18',
                'alumno' => 15,
                'importe_cobro' => 1861,
                'tipo_pago_1' => 7,
                'importe_pago_1' => 1861,
                'referencia_1' => '',
                'tipo_pago_2' => 0,
                'importe_pago_2' => 0,
                'referencia_2' => '',
                'cajero' => 1,
                'quien_paga' => 1,
                'comentario' => '',
                'comentario_ad' => '',
                'cuen_banco' => 0,
                'referencia' => '',
                'importe' => 0,
            ],
            [
                'recibo' => 16,
                'fecha_cobro' => '2010-05-19',
                'hora' => '15:39:04',
                'alumno' => 13,
                'importe_cobro' => 1551,
                'tipo_pago_1' => 7,
                'importe_pago_1' => 1551,
                'referencia_1' => '',
                'tipo_pago_2' => 0,
                'importe_pago_2' => 0,
                'referencia_2' => '',
                'cajero' => 1,
                'quien_paga' => 1,
                'comentario' => '',
                'comentario_ad' => '',
                'cuen_banco' => 0,
                'referencia' => '',
                'importe' => 0,
            ],
            [
                'recibo' => 17,
                'fecha_cobro' => '2010-05-19',
                'hora' => '15:39:52',
                'alumno' => 11,
                'importe_cobro' => 1791,
                'tipo_pago_1' => 1,
                'importe_pago_1' => 1791,
                'referencia_1' => '',
                'tipo_pago_2' => 0,
                'importe_pago_2' => 0,
                'referencia_2' => '',
                'cajero' => 1,
                'quien_paga' => 1,
                'comentario' => '',
                'comentario_ad' => '',
                'cuen_banco' => 0,
                'referencia' => '',
                'importe' => 0,
            ],
            [
                'recibo' => 18,
                'fecha_cobro' => '2010-05-19',
                'hora' => '15:41:07',
                'alumno' => 10,
                'importe_cobro' => 1791,
                'tipo_pago_1' => 1,
                'importe_pago_1' => 1791,
                'referencia_1' => '',
                'tipo_pago_2' => 0,
                'importe_pago_2' => 0,
                'referencia_2' => '',
                'cajero' => 1,
                'quien_paga' => 1,
                'comentario' => '',
                'comentario_ad' => '',
                'cuen_banco' => 0,
                'referencia' => '',
                'importe' => 0,
            ],
            [
                'recibo' => 19,
                'fecha_cobro' => '2010-05-19',
                'hora' => '15:42:08',
                'alumno' => 9,
                'importe_cobro' => 1861,
                'tipo_pago_1' => 1,
                'importe_pago_1' => 1861,
                'referencia_1' => '',
                'tipo_pago_2' => 0,
                'importe_pago_2' => 0,
                'referencia_2' => '',
                'cajero' => 1,
                'quien_paga' => 1,
                'comentario' => '',
                'comentario_ad' => '',
                'cuen_banco' => 0,
                'referencia' => '',
                'importe' => 0,
            ],
            [
                'recibo' => 20,
                'fecha_cobro' => '2010-05-19',
                'hora' => '15:42:48',
                'alumno' => 6,
                'importe_cobro' => 1861,
                'tipo_pago_1' => 1,
                'importe_pago_1' => 1861,
                'referencia_1' => '',
                'tipo_pago_2' => 0,
                'importe_pago_2' => 0,
                'referencia_2' => '',
                'cajero' => 1,
                'quien_paga' => 1,
                'comentario' => '',
                'comentario_ad' => '',
                'cuen_banco' => 0,
                'referencia' => '',
                'importe' => 0,
            ],
            [
                'recibo' => 21,
                'fecha_cobro' => '2010-05-19',
                'hora' => '15:43:47',
                'alumno' => 5,
                'importe_cobro' => 1861,
                'tipo_pago_1' => 1,
                'importe_pago_1' => 1861,
                'referencia_1' => '',
                'tipo_pago_2' => 0,
                'importe_pago_2' => 0,
                'referencia_2' => '',
                'cajero' => 1,
                'quien_paga' => 1,
                'comentario' => '',
                'comentario_ad' => '',
                'cuen_banco' => 0,
                'referencia' => '',
                'importe' => 0,
            ],
            [
                'recibo' => 22,
                'fecha_cobro' => '2010-05-19',
                'hora' => '15:44:30',
                'alumno' => 8,
                'importe_cobro' => 1861,
                'tipo_pago_1' => 1,
                'importe_pago_1' => 1861,
                'referencia_1' => '',
                'tipo_pago_2' => 0,
                'importe_pago_2' => 0,
                'referencia_2' => '',
                'cajero' => 1,
                'quien_paga' => 1,
                'comentario' => '',
                'comentario_ad' => '',
                'cuen_banco' => 0,
                'referencia' => '',
                'importe' => 0,
            ],
            // Añadir más registros según sea necesario
        ];
        foreach ($registros as $registro) {
            DB::table('cobranza_diaria')->updateOrInsert(
                [
                    'recibo' => $registro['recibo'],
                    'fecha_cobro' => $registro['fecha_cobro'],
                    'hora' => $registro['hora'],                    
                ],
                $registro
            );
        }
    }
}
