<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DocumentosCobranzaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $registros = [
            // [
            //     'alumno' => 1,
            //     'producto' => 24,
            //     'numero_doc' => '201009',
            //     'fecha' => '2010-09-10',
            //     'descuento' => 0,
            //     'importe' => 1560,
            //     'fecha_cobro' => '2010-10-08',
            //     'importe_pago' => 1560,
            //     'ref' => 'COL',
            //     'grupo' => 'DEUDOR',
            //     'orden' => 1,
            //     'baja' => '',
            // ],
            // [
            //     'alumno' => 1,
            //     'producto' => 24,
            //     'numero_doc' => '201010',
            //     'fecha' => '2010-10-10',
            //     'descuento' => 0,
            //     'importe' => 1560,
            //     'fecha_cobro' => '2010-10-08',
            //     'importe_pago' => 1560,
            //     'ref' => 'COL',
            //     'grupo' => 'DEUDOR',
            //     'orden' => 1,
            //     'baja' => '',
            // ],
            // [
            //     'alumno' => 1,
            //     'producto' => 24,
            //     'numero_doc' => '201011',
            //     'fecha' => '2010-11-10',
            //     'descuento' => 0,
            //     'importe' => 1560,
            //     'fecha_cobro' => '',
            //     'importe_pago' => 0,
            //     'ref' => 'COL',
            //     'grupo' => 'DEUDOR',
            //     'orden' => 1,
            //     'baja' => '',
            // ],
            // [
            //     'alumno' => 1,
            //     'producto' => 24,
            //     'numero_doc' => '201012',
            //     'fecha' => '2010-12-10',
            //     'descuento' => 0,
            //     'importe' => 1560,
            //     'fecha_cobro' => '',
            //     'importe_pago' => 0,
            //     'ref' => 'COL',
            //     'grupo' => 'DEUDOR',
            //     'orden' => 1,
            //     'baja' => '',
            // ],
            // [
            //     'alumno' => 1,
            //     'producto' => 78,
            //     'numero_doc' => '201004',
            //     'fecha' => '2010-04-20',
            //     'descuento' => 0,
            //     'importe' => 1500,
            //     'fecha_cobro' => '2010-07-19',
            //     'importe_pago' => 1500,
            //     'ref' => '',
            //     'grupo' => 'DEUDOR',
            //     'orden' => 1,
            //     'baja' => '',
            // ],
            // [
            //     'alumno' => 1,
            //     'producto' => 8,
            //     'numero_doc' => '9',
            //     'fecha' => '2010-05-10',
            //     'descuento' => 0,
            //     'importe' => 1300,
            //     'fecha_cobro' => '2010-05-10',
            //     'importe_pago' => 1300,
            //     'ref' => 'COL',
            //     'grupo' => 'DEUDOR',
            //     'orden' => 1,
            //     'baja' => '',
            // ],
            // [
            //     'alumno' => 1,
            //     'producto' => 8,
            //     'numero_doc' => '10',
            //     'fecha' => '2010-06-10',
            //     'descuento' => 0,
            //     'importe' => 1300,
            //     'fecha_cobro' => '2010-08-16',
            //     'importe_pago' => 1300,
            //     'ref' => 'COL',
            //     'grupo' => 'DEUDOR',
            //     'orden' => 1,
            //     'baja' => '',
            // ],
            // [
            //     'alumno' => 1,
            //     'producto' => 9999,
            //     'numero_doc' => '201009',
            //     'fecha' => '2010-09-14',
            //     'descuento' => 0,
            //     'importe' => 240,
            //     'fecha_cobro' => '2010-10-08',
            //     'importe_pago' => 240,
            //     'ref' => 'REC',
            //     'grupo' => 'DEUDOR',
            //     'orden' => 1,
            //     'baja' => '',
            // ],
            // [
            //     'alumno' => 1,
            //     'producto' => 9999,
            //     'numero_doc' => '201011',
            //     'fecha' => '2010-11-11',
            //     'descuento' => 0,
            //     'importe' => 240,
            //     'fecha_cobro' => '',
            //     'importe_pago' => 0,
            //     'ref' => 'REC',
            //     'grupo' => 'DEUDOR',
            //     'orden' => 1,
            //     'baja' => '',
            // ],
            // [
            //     'alumno' => 1,
            //     'producto' => 9999,
            //     'numero_doc' => '201012',
            //     'fecha' => '2010-12-10',
            //     'descuento' => 0,
            //     'importe' => 240,
            //     'fecha_cobro' => '',
            //     'importe_pago' => 0,
            //     'ref' => 'REC',
            //     'grupo' => 'DEUDOR',
            //     'orden' => 1,
            //     'baja' => '',
            // ],
            // [
            //     'alumno' => 2,
            //     'producto' => 10,
            //     'numero_doc' => '201009',
            //     'fecha' => '2010-09-10',
            //     'descuento' => 0,
            //     'importe' => 1551,
            //     'fecha_cobro' => '2010-09-10',
            //     'importe_pago' => 1551,
            //     'ref' => 'COL',
            //     'grupo' => 'DEUDOR',
            //     'orden' => 1,
            //     'baja' => '*',
            // ],
            // [
            //     'alumno' => 2,
            //     'producto' => 10,
            //     'numero_doc' => '201010',
            //     'fecha' => '2010-10-10',
            //     'descuento' => 0,
            //     'importe' => 1551,
            //     'fecha_cobro' => '2011-06-17',
            //     'importe_pago' => 1551,
            //     'ref' => 'COL',
            //     'grupo' => 'DEUDOR',
            //     'orden' => 1,
            //     'baja' => '*',
            // ],
            // [
            //     'alumno' => 2,
            //     'producto' => 103,
            //     'numero_doc' => '1112',
            //     'fecha' => '2011-06-17',
            //     'descuento' => 0,
            //     'importe' => 3350,
            //     'fecha_cobro' => '2011-06-17',
            //     'importe_pago' => 1559,
            //     'ref' => 'INS',
            //     'grupo' => 'DEUDOR',
            //     'orden' => 1,
            //     'baja' => '*',
            // ],
            // [
            //     'alumno' => 2,
            //     'producto' => 20,
            //     'numero_doc' => '1',
            //     'fecha' => '2010-05-31',
            //     'descuento' => 0,
            //     'importe' => 2700,
            //     'fecha_cobro' => '2010-04-13',
            //     'importe_pago' => 2700,
            //     'ref' => '',
            //     'grupo' => 'DEUDOR',
            //     'orden' => 1,
            //     'baja' => '*',
            // ],
            // [
            //     'alumno' => 2,
            //     'producto' => 9,
            //     'numero_doc' => '9',
            //     'fecha' => '2010-05-10',
            //     'descuento' => 0,
            //     'importe' => 1300,
            //     'fecha_cobro' => '2010-05-06',
            //     'importe_pago' => 1300,
            //     'ref' => 'COL',
            //     'grupo' => 'DEUDOR',
            //     'orden' => 1,
            //     'baja' => '*',
            // ],
            // [
            //     'alumno' => 2,
            //     'producto' => 9,
            //     'numero_doc' => '10',
            //     'fecha' => '2010-06-10',
            //     'descuento' => 0,
            //     'importe' => 1300,
            //     'fecha_cobro' => '2010-06-04',
            //     'importe_pago' => 1300,
            //     'ref' => 'COL',
            //     'grupo' => 'DEUDOR',
            //     'orden' => 1,
            //     'baja' => '*',
            // ],
            // [
            //     'alumno' => 2,
            //     'producto' => 9999,
            //     'numero_doc' => '201010',
            //     'fecha' => '2010-10-11',
            //     'descuento' => 0,
            //     'importe' => 240,
            //     'fecha_cobro' => '2011-06-17',
            //     'importe_pago' => 240,
            //     'ref' => 'REC',
            //     'grupo' => 'DEUDOR',
            //     'orden' => 1,
            //     'baja' => '*',
            // ],
            // [
            //     'alumno' => 3,
            //     'producto' => 103,
            //     'numero_doc' => '1112',
            //     'fecha' => '2011-06-03',
            //     'descuento' => 0,
            //     'importe' => 3350,
            //     'fecha_cobro' => '2011-04-15',
            //     'importe_pago' => 3350,
            //     'ref' => 'INS',
            //     'grupo' => 'KINDER II',
            //     'orden' => 1,
            //     'baja' => '',
            // ],
            // [
            //     'alumno' => 3,
            //     'producto' => 24,
            //     'numero_doc' => '9',
            //     'fecha' => '2010-05-10',
            //     'descuento' => 0,
            //     'importe' => 1560,
            //     'fecha_cobro' => '2010-04-28',
            //     'importe_pago' => 1560,
            //     'ref' => 'COL',
            //     'grupo' => 'KINDER II',
            //     'orden' => 1,
            //     'baja' => '',
            // ],
            // [
            //     'alumno' => 3,
            //     'producto' => 24,
            //     'numero_doc' => '10',
            //     'fecha' => '2010-06-10',
            //     'descuento' => 0,
            //     'importe' => 1560,
            //     'fecha_cobro' => '2010-06-03',
            //     'importe_pago' => 1560,
            //     'ref' => 'COL',
            //     'grupo' => 'KINDER II',
            //     'orden' => 1,
            //     'baja' => '',
            // ],
            // [
            //     'alumno' => 3,
            //     'producto' => 26,
            //     'numero_doc' => '201009',
            //     'fecha' => '2010-09-10',
            //     'descuento' => 0,
            //     'importe' => 1861,
            //     'fecha_cobro' => '2010-09-03',
            //     'importe_pago' => 1861,
            //     'ref' => 'COL',
            //     'grupo' => 'KINDER II',
            //     'orden' => 1,
            //     'baja' => '',
            // ],
            // [
            //     'alumno' => 3,
            //     'producto' => 26,
            //     'numero_doc' => '201010',
            //     'fecha' => '2010-10-10',
            //     'descuento' => 0,
            //     'importe' => 1861,
            //     'fecha_cobro' => '2010-09-29',
            //     'importe_pago' => 1861,
            //     'ref' => 'COL',
            //     'grupo' => 'KINDER II',
            //     'orden' => 1,
            //     'baja' => '',
            // ],
            // [
            //     'alumno' => 3,
            //     'producto' => 26,
            //     'numero_doc' => '201011',
            //     'fecha' => '2010-11-10',
            //     'descuento' => 0,
            //     'importe' => 1861,
            //     'fecha_cobro' => '2010-11-01',
            //     'importe_pago' => 1861,
            //     'ref' => 'COL',
            //     'grupo' => 'KINDER II',
            //     'orden' => 1,
            //     'baja' => '',
            // ],
            // [
            //     'alumno' => 3,
            //     'producto' => 26,
            //     'numero_doc' => '201012',
            //     'fecha' => '2010-12-10',
            //     'descuento' => 0,
            //     'importe' => 1861,
            //     'fecha_cobro' => '2010-12-22',
            //     'importe_pago' => 1861,
            //     'ref' => 'COL',
            //     'grupo' => 'KINDER II',
            //     'orden' => 1,
            //     'baja' => '',
            // ],
            // [
            //     'alumno' => 3,
            //     'producto' => 26,
            //     'numero_doc' => '201101',
            //     'fecha' => '2011-01-10',
            //     'descuento' => 0,
            //     'importe' => 1861,
            //     'fecha_cobro' => '2010-11-23',
            //     'importe_pago' => 1861,
            //     'ref' => 'COL',
            //     'grupo' => 'KINDER II',
            //     'orden' => 1,
            //     'baja' => '',
            // ],
            // [
            //     'alumno' => 3,
            //     'producto' => 26,
            //     'numero_doc' => '201102',
            //     'fecha' => '2011-02-10',
            //     'descuento' => 0,
            //     'importe' => 1861,
            //     'fecha_cobro' => '2011-02-09',
            //     'importe_pago' => 1861,
            //     'ref' => 'COL',
            //     'grupo' => 'KINDER II',
            //     'orden' => 1,
            //     'baja' => '',
            // ],
            // [
            //     'alumno' => 3,
            //     'producto' => 26,
            //     'numero_doc' => '201103',
            //     'fecha' => '2011-03-10',
            //     'descuento' => 0,
            //     'importe' => 1861,
            //     'fecha_cobro' => '2011-03-02',
            //     'importe_pago' => 1861,
            //     'ref' => 'COL',
            //     'grupo' => 'KINDER II',
            //     'orden' => 1,
            //     'baja' => '',
            // ],
            // [
            //     'alumno' => 3,
            //     'producto' => 26,
            //     'numero_doc' => '201104',
            //     'fecha' => '2011-04-10',
            //     'descuento' => 0,
            //     'importe' => 1861,
            //     'fecha_cobro' => '2011-04-08',
            //     'importe_pago' => 1861,
            //     'ref' => 'COL',
            //     'grupo' => 'KINDER II',
            //     'orden' => 1,
            //     'baja' => '',
            // ],
            // [
            //     'alumno' => 3,
            //     'producto' => 26,
            //     'numero_doc' => '201105',
            //     'fecha' => '2011-05-10',
            //     'descuento' => 0,
            //     'importe' => 1861,
            //     'fecha_cobro' => '2011-04-20',
            //     'importe_pago' => 1861,
            //     'ref' => 'COL',
            //     'grupo' => 'KINDER II',
            //     'orden' => 1,
            //     'baja' => '',
            // ],
            // [
            //     'alumno' => 3,
            //     'producto' => 26,
            //     'numero_doc' => '201106',
            //     'fecha' => '2011-06-10',
            //     'descuento' => 0,
            //     'importe' => 1861,
            //     'fecha_cobro' => '2011-05-31',
            //     'importe_pago' => 1861,
            //     'ref' => 'COL',
            //     'grupo' => 'KINDER II',
            //     'orden' => 1,
            //     'baja' => '',
            // ],
            // [
            //     'alumno' => 3,
            //     'producto' => 28,
            //     'numero_doc' => '201109',
            //     'fecha' => '2011-09-10',
            //     'descuento' => 0,
            //     'importe' => 2128,
            //     'fecha_cobro' => '2011-09-05',
            //     'importe_pago' => 2128,
            //     'ref' => 'COL',
            //     'grupo' => 'KINDER II',
            //     'orden' => 1,
            //     'baja' => '',
            // ],
            // [
            //     'alumno' => 3,
            //     'producto' => 28,
            //     'numero_doc' => '201110',
            //     'fecha' => '2011-10-10',
            //     'descuento' => 0,
            //     'importe' => 2128,
            //     'fecha_cobro' => '2011-09-30',
            //     'importe_pago' => 2128,
            //     'ref' => 'COL',
            //     'grupo' => 'KINDER II',
            //     'orden' => 1,
            //     'baja' => '',
            // ],
            // [
            //     'alumno' => 3,
            //     'producto' => 28,
            //     'numero_doc' => '201111',
            //     'fecha' => '2011-11-10',
            //     'descuento' => 0,
            //     'importe' => 2128,
            //     'fecha_cobro' => '2011-10-27',
            //     'importe_pago' => 2128,
            //     'ref' => 'COL',
            //     'grupo' => 'KINDER II',
            //     'orden' => 1,
            //     'baja' => '',
            // ],
            // [
            //     'alumno' => 3,
            //     'producto' => 28,
            //     'numero_doc' => '201112',
            //     'fecha' => '2011-12-10',
            //     'descuento' => 0,
            //     'importe' => 2128,
            //     'fecha_cobro' => '2011-11-25',
            //     'importe_pago' => 2128,
            //     'ref' => 'COL',
            //     'grupo' => 'KINDER II',
            //     'orden' => 1,
            //     'baja' => '',
            // ],
            // [
            //     'alumno' => 3,
            //     'producto' => 28,
            //     'numero_doc' => '201201',
            //     'fecha' => '2012-01-10',
            //     'descuento' => 0,
            //     'importe' => 2128,
            //     'fecha_cobro' => '2011-12-28',
            //     'importe_pago' => 2128,
            //     'ref' => 'COL',
            //     'grupo' => 'KINDER II',
            //     'orden' => 1,
            //     'baja' => '',
            // ],
            // [
            //     'alumno' => 3,
            //     'producto' => 28,
            //     'numero_doc' => '201202',
            //     'fecha' => '2012-02-10',
            //     'descuento' => 0,
            //     'importe' => 2128,
            //     'fecha_cobro' => '2012-02-10',
            //     'importe_pago' => 2128,
            //     'ref' => 'COL',
            //     'grupo' => 'KINDER II',
            //     'orden' => 1,
            //     'baja' => '',
            // ],
            // [
            //     'alumno' => 3,
            //     'producto' => 28,
            //     'numero_doc' => '201203',
            //     'fecha' => '2012-03-10',
            //     'descuento' => 0,
            //     'importe' => 2128,
            //     'fecha_cobro' => '',
            //     'importe_pago' => 0,
            //     'ref' => 'COL',
            //     'grupo' => 'KINDER II',
            //     'orden' => 1,
            //     'baja' => '',
            // ],
            // [
            //     'alumno' => 3,
            //     'producto' => 28,
            //     'numero_doc' => '201204',
            //     'fecha' => '2012-04-10',
            //     'descuento' => 0,
            //     'importe' => 2128,
            //     'fecha_cobro' => '',
            //     'importe_pago' => 0,
            //     'ref' => 'COL',
            //     'grupo' => 'KINDER II',
            //     'orden' => 1,
            //     'baja' => '',
            // ],
            // [
            //     'alumno' => 3,
            //     'producto' => 28,
            //     'numero_doc' => '201205',
            //     'fecha' => '2012-05-10',
            //     'descuento' => 0,
            //     'importe' => 2128,
            //     'fecha_cobro' => '',
            //     'importe_pago' => 0,
            //     'ref' => 'COL',
            //     'grupo' => 'KINDER II',
            //     'orden' => 1,
            //     'baja' => '',
            // ],
            // [
            //     'alumno' => 3,
            //     'producto' => 28,
            //     'numero_doc' => '201206',
            //     'fecha' => '2012-06-10',
            //     'descuento' => 0,
            //     'importe' => 2128,
            //     'fecha_cobro' => '',
            //     'importe_pago' => 0,
            //     'ref' => 'COL',
            //     'grupo' => 'KINDER II',
            //     'orden' => 1,
            //     'baja' => '',
            // ],
            // [
            //     'alumno' => 3,
            //     'producto' => 47,
            //     'numero_doc' => '1',
            //     'fecha' => '2010-03-16',
            //     'descuento' => 0,
            //     'importe' => 2370,
            //     'fecha_cobro' => '2010-03-17',
            //     'importe_pago' => 2370,
            //     'ref' => 'INS',
            //     'grupo' => 'KINDER II',
            //     'orden' => 1,
            //     'baja' => '',
            // ],
        ];
        foreach ($registros as $registro) {
            DB::table('documentos_cobranza')->updateOrInsert(
                [
                    'alumno' => $registro['alumno'],
                    'producto' => $registro['producto'],
                    'numero_doc' => $registro['numero_doc'],
                    'fecha' => $registro['fecha']
                ],
                $registro
            );
        }
    }
}
