<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ReferenciaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $registros =[
            [
                'numero'=>1,
                'referencia'=>'COL',
                'descripcion'=>'Colegiatura',
                'baja'=>''
            ],
            [
                'numero'=>2,
                'referencia'=>'DEU',
                'descripcion'=>'Deudor',
                'baja'=>''
            ],
            [
                'numero'=>3,
                'referencia'=>'INS',
                'descripcion'=>'Inscripcion',
                'baja'=>''
            ],
            [
                'numero'=>4,
                'referencia'=>'PAR',
                'descripcion'=>'',
                'baja'=>''
            ],
            [
                'numero'=>5,
                'referencia'=>'REC',
                'descripcion'=>'',
                'baja'=>''
            ],
            [
                'numero'=>6,
                'referencia'=>'SE1',
                'descripcion'=>'',
                'baja'=>''
            ],
            [
                'numero'=>7,
                'referencia'=>'SE2',
                'descripcion'=>'',
                'baja'=>''
            ],
            [
                'numero'=>8,
                'referencia'=>'SE3',
                'descripcion'=>'',
                'baja'=>''
            ],
            [
                'numero'=>9,
                'referencia'=>'SE4',
                'descripcion'=>'',
                'baja'=>''
            ],
            [
                'numero'=>10,
                'referencia'=>'SE5',
                'descripcion'=>'',
                'baja'=>''
            ],
            [
                'numero'=>11,
                'referencia'=>'SEE',
                'descripcion'=>'',
                'baja'=>''
            ],
            [
                'numero'=>12,
                'referencia'=>'SMT',
                'descripcion'=>'',
                'baja'=>''
            ],
            [
                'numero'=>13,
                'referencia'=>'SOB',
                'descripcion'=>'',
                'baja'=>''
            ],
            [
                'numero'=>14,
                'referencia'=>'STC',
                'descripcion'=>'',
                'baja'=>''
            ],
            [
                'numero'=>15,
                'referencia'=>'TAJ',
                'descripcion'=>'',
                'baja'=>''
            ],
            [
                'numero'=>16,
                'referencia'=>'TTD',
                'descripcion'=>'',
                'baja'=>''
            ],
            [
                'numero'=>17,
                'referencia'=>'TTS',
                'descripcion'=>'',
                'baja'=>''
            ],
            [
                'numero'=>18,
                'referencia'=>'TVE',
                'descripcion'=>'',
                'baja'=>''
            ],
        ];
        foreach ($registros as $registro){
            DB::table('referencias')->updateOrInsert(
                ['numero'=>$registro["numero"]],
                $registro
            );
        }
    }
}
